#scheme: Muse Mist Pisces
scheme: Gemini

motion: false

minify: true

# Post meta display settings
post_meta:
  # item_text: true
  # created_at: true
  # 主要是这一部分
  updated_at:
    # 显示更新时间
    enable: false
    # 与创建时间不同时才显示
    another_day: true
  # categories: true

# Easily enable fast Ajax navigation on your website.
# For more information: https://github.com/next-theme/pjax
pjax: true

fancybox: true
lazyload: true
pangu: true

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  # commonweal: /404/ || fa fa-heartbeat

avatar:
  #url: /images/safari-pinned-tab.svg
  url: https://z3.ax1x.com/2021/11/17/I5l2k9.png
  rounded: true
  #rotated: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: 4A9w-gAYGskhjcVDdWrbrcVSG0LOY4_NQjYsoKGPEhE

#  Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification: code-AYaWNUQGUY

custom_file_path:
  style: source/_data/styles.styl

seo: true

# Math Formulas Render Support
math:
  # Default (false) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in front-matter.
  # If you set it to true, it will load mathjax / katex srcipt EVERY PAGE.
  every_page: false

  mathjax:
    enable: true
    # Available values: none | ams | all
    tags: none

# Local search
local_search:
  enable: true

codeblock:
  copy_button:
    enable: true
    #style: mac

darkmode: true

sidebar:
  display: post

toc:
  expand_all: true

back2top:
  # Scroll percent label in b2t button.
  scrollpercent: true

footer:
  since: 2021
  powered: false
  icon:
    animated: true

# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: false
  appId: iDrB7vc3mJhoro1NqRmbSrrK-MdYXbMMI
  appKey: k2nWbxuzuLR5cIne6MrSVcqX
  lang: en
  placeholder: ...
  avatar: mp
  meta: [nick]
  pageSize: 5
